version: 2

sources:
 
  - name: BNG_WAREHOUSE
    schema: AZURE_DB_BNG
    database:  FIVETRAN_CONNECT_DB
    tables:
      - name: USR_LOCATIONS
        identifier: USR_LOCATIONS
      - name: USR_DELIVERED_ORDERS
        identifier: USR_DELIVERED_ORDERS
      - name: USR_DETAILS
        identifier: USR_DETAILS      
      - name: USR_OPEN_ORDERS
        identifier: USR_OPEN_ORDERS 
      - name: USR_PICKED_ORDERS
        identifier: USR_PICKED_ORDERS
      - name: USR_SHIPPED_ORDERS
        identifier: USR_SHIPPED_ORDERS

  - name: HYD_WAREHOUSE
    schema: AZURE_DB_HYD
    database:  FIVETRAN_CONNECT_DB
    tables:
      - name: USR_LOCATIONS
        identifier: USR_LOCATIONS
      - name: USR_DELIVERED_ORDERS
        identifier: USR_DELIVERED_ORDERS
      - name: USR_DETAILS
        identifier: USR_DETAILS      
      - name: USR_OPEN_ORDERS
        identifier: USR_OPEN_ORDERS 
      - name: USR_PICKED_ORDERS
        identifier: USR_PICKED_ORDERS
      - name: USR_SHIPPED_ORDERS
        identifier: USR_SHIPPED_ORDERS

  - name: KLP_WAREHOUSE
    schema: AZURE_DB_KLP
    database:  FIVETRAN_CONNECT_DB
    tables:
      - name: USR_LOCATIONS
        identifier: USR_LOCATIONS
      - name: USR_DELIVERED_ORDERS
        identifier: USR_DELIVERED_ORDERS
      - name: USR_DETAILS
        identifier: USR_DETAILS      
      - name: USR_OPEN_ORDERS
        identifier: USR_OPEN_ORDERS 
      - name: USR_PICKED_ORDERS
        identifier: USR_PICKED_ORDERS
      - name: USR_SHIPPED_ORDERS
        identifier: USR_SHIPPED_ORDERS

  - name: VSKP_WAREHOUSE
    schema: AZURE_DB_VSKP
    database:  FIVETRAN_CONNECT_DB
    tables:
      - name: USR_LOCATIONS
        identifier: USR_LOCATIONS
      - name: USR_DELIVERED_ORDERS
        identifier: USR_DELIVERED_ORDERS
      - name: USR_DETAILS
        identifier: USR_DETAILS      
      - name: USR_OPEN_ORDERS
        identifier: USR_OPEN_ORDERS 
      - name: USR_PICKED_ORDERS
        identifier: USR_PICKED_ORDERS
      - name: USR_SHIPPED_ORDERS
        identifier: USR_SHIPPED_ORDERS