SELECT DISTINCT * FROM
(
SELECT 'USR_LOCATIONS' AS SRCTBLNAME, 'DBT_TEST' AS SYSTEMNAME, 'EDW_LOCATION' AS TBLNAME, 'LOC_KEY' AS DEST_CHANGE_KEY, 'USR_LOCATIONS_CHANGES' AS SOURCE_CHANGE_TBL, 'LOCATION_ID' AS SOURCE_CHANGE_KEY, 'SCD1' AS SCDTYPE , null AS SRCTBLCONDITION 
)